import styles from './about.module.scss';

const About = () => {
  return (
    <section className="section" id="about">
      <div className={`${styles.aboutContainer} container`}>
        <div className={styles.wrapper}>
          <h2 className={styles.title}>
            A Story that started with
            <span className={styles.titleAccent}> one simple ape</span>
          </h2>
          <p className={styles.textFistBlock}>
            Who got fed up with boring and hypocritic commonplace this is how
            the idea of escaping and dynamic journey on the yacht
          </p>
        </div>

        <p className={styles.textSecondBlock}>
          Each artwork in the collection tells a story of one journey. Arts are
          randomly generated by users
        </p>
      </div>

      <div className={styles.banner}>
        <div className={styles.slide}>
          <p className={styles.item}>Destroy stereotypes</p>
          <p className={styles.item}>Have no limits</p>
          <p className={styles.item}>Break rules</p>
        </div>

        <div className={styles.slide}>
          <p className={styles.item}>Destroy stereotypes</p>
          <p className={styles.item}>Have no limits</p>
          <p className={styles.item}>Break rules</p>
        </div>

        <div className={styles.slide}>
          <p className={styles.item}>Destroy stereotypes</p>
          <p className={styles.item}>Have no limits</p>
          <p className={styles.item}>Break rules</p>
        </div>
      </div>
    </section>
  );
};

export default About;
